import {BOTTOM_TAB_NAVIGATOR, SHOP_SCREEN, SPLASH_SCREEN} from './Screens';
export const INITIAL_SCREEN = BOTTOM_TAB_NAVIGATOR;
// export const INITIAL_SCREEN = SHOP_SCREEN;
export const TIME_SPLASH = 3000;
export const SERVER_ADDRESS = 'http://69.197.134.101:8080/';
